version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers-legacy
        environment:
          APP_ENV: local
          APP_DEBUG: true
          APP_KEY: kjcndjjksddwdwdw
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: sales
          DB_USERNAME: root
          DB_PASSWORD: password
          CACHE_DRIVER: memcached
          QUEUE_DRIVER: sync
      - image: mysql:5.6
        environment:
          MYSQL_DATABASE: sales
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get -y install git unzip zlib1g-dev
      - run: sudo docker-php-ext-install pdo pdo_mysql zip
      - run: composer install -n --prefer-dist
      #Migrations
      - run: php artisan migrate --force
      #Seeders
      - run: php artisan db:seed --class=ItemsTableSeeder
      - run: php artisan db:seed --class=SalesTableSeeder
      - run: php artisan db:seed --class=SalesItemsTableSeeder
  
      # run tests with phpunit
      - run: ./vendor/bin/phpunit
      - store_test_results:
          path: tests/_output
