version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.3-stretch-node-browsers
          
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_DATABASE: sales
          MYSQL_ROOT_PASSWORD: password          
          
    steps:
      - checkout
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: composer install -n --prefer-dist
            
      #Migrations
      - run: php artisan migrate
      
      #Seeders
      - run: php artisan make:seeder ItemsTableSeeder
      - run: php artisan make:seeder SalesTableSeeder
      - run: php artisan make:seeder SalesItemsSeeder      
      
      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
      - store_test_results:
          path: tests/_output
