version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers-legacy
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_DATABASE: sales
          MYSQL_ROOT_PASSWORD: password          
          
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      #Migrations
      - run: php artisan migrate --force
      #Seeders
      - run: php artisan make:seeder ItemsTableSeeder
      - run: php artisan make:seeder SalesTableSeeder
      - run: php artisan make:seeder SalesItemsSeeder      
      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
      - store_test_results:
          path: tests/_output
